/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiProductsIndexRouteImport } from './routes/api/products.index'
import { Route as ApiProductsIdRouteImport } from './routes/api/products.$id'

const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsIndexRoute = ApiProductsIndexRouteImport.update({
  id: '/api/products/',
  path: '/api/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsIdRoute = ApiProductsIdRouteImport.update({
  id: '/api/products/$id',
  path: '/api/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/products': typeof ProductsRoute
  '/api/products/$id': typeof ApiProductsIdRoute
  '/api/products/': typeof ApiProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/products': typeof ProductsRoute
  '/api/products/$id': typeof ApiProductsIdRoute
  '/api/products': typeof ApiProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/products': typeof ProductsRoute
  '/api/products/$id': typeof ApiProductsIdRoute
  '/api/products/': typeof ApiProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/products' | '/api/products/$id' | '/api/products/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/products' | '/api/products/$id' | '/api/products'
  id: '__root__' | '/' | '/products' | '/api/products/$id' | '/api/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProductsRoute: typeof ProductsRoute
  ApiProductsIdRoute: typeof ApiProductsIdRoute
  ApiProductsIndexRoute: typeof ApiProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/': {
      id: '/api/products/'
      path: '/api/products'
      fullPath: '/api/products/'
      preLoaderRoute: typeof ApiProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/$id': {
      id: '/api/products/$id'
      path: '/api/products/$id'
      fullPath: '/api/products/$id'
      preLoaderRoute: typeof ApiProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProductsRoute: ProductsRoute,
  ApiProductsIdRoute: ApiProductsIdRoute,
  ApiProductsIndexRoute: ApiProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
